#! /bin/bash
limit=22
for (( i=1300; i>0; i--)); do
	counter=0
	python benchmark_tx_test.py &
	while [ $counter != $limit ]; do
		echo "$counter seconds so far...";
		sleep 1
		let "counter = $counter + 1"
	done
	if [ $counter = $limit ]; then
		pkill -f "python benchmark_tx_test.py"			   
	fi
done


